"""Added user_stock association table

Revision ID: 299d75cad706
Revises: 4b9fb827aead
Create Date: 2023-12-12 10:56:27.967312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299d75cad706'
down_revision = '4b9fb827aead'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
