"""Removed price column from Stock table

Revision ID: 3b806c7838c1
Revises: 663b6499ef29
Create Date: 2023-12-13 02:11:03.755711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b806c7838c1'
down_revision = '663b6499ef29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('price', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
