"""Added date_added column to user_stock table

Revision ID: 484d0736541c
Revises: 299d75cad706
Create Date: 2023-12-12 15:26:04.952706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484d0736541c'
down_revision = '299d75cad706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stock', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stock', 'date_added')
    # ### end Alembic commands ###
