"""Creates 90-day moving average column in stocks table

Revision ID: 663b6499ef29
Revises: b0ad69edb5f2
Create Date: 2023-12-13 01:48:44.275157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663b6499ef29'
down_revision = 'b0ad69edb5f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('90-D MA', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', '90-D MA')
    # ### end Alembic commands ###
