"""Changed to a stock analyst rating system

Revision ID: b0ad69edb5f2
Revises: 484d0736541c
Create Date: 2023-12-13 00:15:25.371686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ad69edb5f2'
down_revision = '484d0736541c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
