"""Added comment field to MarketData

Revision ID: d41283028fa9
Revises: a89d335bed1c
Create Date: 2023-12-14 01:24:42.755753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41283028fa9'
down_revision = 'a89d335bed1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'comment')
    # ### end Alembic commands ###
